CREATE TABLE 'campaign_freegacha_data' ('id' INTEGER NOT NULL, 'campaign_id' INTEGER NOT NULL, 'gacha_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "campaign_freegacha_data" VALUES(1,1,30007);
INSERT INTO "campaign_freegacha_data" VALUES(2,1,30008);
INSERT INTO "campaign_freegacha_data" VALUES(3,2,30012);
INSERT INTO "campaign_freegacha_data" VALUES(4,2,40001);
INSERT INTO "campaign_freegacha_data" VALUES(6,3,30022);
INSERT INTO "campaign_freegacha_data" VALUES(7,3,50023);
INSERT INTO "campaign_freegacha_data" VALUES(8,3,30024);
INSERT INTO "campaign_freegacha_data" VALUES(9,4,30026);
INSERT INTO "campaign_freegacha_data" VALUES(10,4,50027);
