CREATE TABLE 'fke_happening_list' ('happening_id' INTEGER NOT NULL, 'happening_name' TEXT NOT NULL, PRIMARY KEY('happening_id'));
INSERT INTO "fke_happening_list" VALUES(1,'Mesarthim');
INSERT INTO "fke_happening_list" VALUES(2,'Banana Jump');
INSERT INTO "fke_happening_list" VALUES(3,'Banana Slide');
INSERT INTO "fke_happening_list" VALUES(4,'Ayumi''s Fan');
INSERT INTO "fke_happening_list" VALUES(5,'The Magistrate');
INSERT INTO "fke_happening_list" VALUES(6,'Geyser');
INSERT INTO "fke_happening_list" VALUES(7,'Tornado');
INSERT INTO "fke_happening_list" VALUES(8,'Headwind');
INSERT INTO "fke_happening_list" VALUES(9,'Downpour');
INSERT INTO "fke_happening_list" VALUES(10,'Ziz');
INSERT INTO "fke_happening_list" VALUES(11,'Lightning');
INSERT INTO "fke_happening_list" VALUES(12,'Pinball');
INSERT INTO "fke_happening_list" VALUES(13,'Low Swoop');
INSERT INTO "fke_happening_list" VALUES(14,'Among the Stars');
INSERT INTO "fke_happening_list" VALUES(15,'Rocket');
INSERT INTO "fke_happening_list" VALUES(16,'Ninon''s Ninpo');
INSERT INTO "fke_happening_list" VALUES(17,'Stomach Slide');
INSERT INTO "fke_happening_list" VALUES(18,'Tailwind');
INSERT INTO "fke_happening_list" VALUES(19,'Drill');
INSERT INTO "fke_happening_list" VALUES(20,'All Spun Out');
