CREATE TABLE 'login_bonus_message_data' ('id' INTEGER NOT NULL, 'login_bonus_id' INTEGER NOT NULL, 'type' INTEGER NOT NULL, 'day_count' INTEGER NOT NULL, 'luck_pattern' INTEGER NOT NULL, 'rate' INTEGER NOT NULL, 'character_id' INTEGER NOT NULL, 'character_name' TEXT NOT NULL, 'message' TEXT NOT NULL, 'voice_id' INTEGER NOT NULL, PRIMARY KEY('id'));
INSERT INTO "login_bonus_message_data" VALUES(1,60000,1,0,0,1,190804,'Karin','It''s a brand new year, so try your luck and see what fortune is in store. The better results even come with extra-special gifts!',1);
INSERT INTO "login_bonus_message_data" VALUES(2,60000,2,0,1,1,0,'','Today''s fortune is: Princess Luck! Your luck stats are maxed out! You could even defeat a legendary vampire or conquer the world!',0);
INSERT INTO "login_bonus_message_data" VALUES(3,60000,2,0,1,1,0,'','Today''s fortune is: Princess Luck! How crazy is that?! ☆ Eat an onigiri, and your life (and belly) will be filled with happiness!',0);
INSERT INTO "login_bonus_message_data" VALUES(4,60000,2,0,1,2,0,'','Today''s fortune is: Princess Luck! Your luck is worthy of a shogun! With such radiant glory, you''ll be the most popular person in town!',0);
INSERT INTO "login_bonus_message_data" VALUES(5,60000,2,0,2,1,0,'','Today''s fortune is: Great Luck! Fate seems to be on your side! Whatever you do today, it will proceed with maximum efficiency!',0);
INSERT INTO "login_bonus_message_data" VALUES(6,60000,2,0,2,1,0,'','Today''s fortune is: Great Luck! You''ll be everyone''s favorite guy! Someone may even be sneaking up behind you right now... Teehee.',0);
INSERT INTO "login_bonus_message_data" VALUES(7,60000,2,0,2,2,0,'','Today''s fortune is: Great Luck! You''ll effortlessly find success! Now''s the time to unearth hidden skills and become a real whiz boy!',0);
INSERT INTO "login_bonus_message_data" VALUES(8,60000,2,0,3,1,0,'','Today''s fortune is: Good Luck! You might attract impressive profits! For an extra karmic boost, grab a taiyaki as your lucky item!',0);
INSERT INTO "login_bonus_message_data" VALUES(9,60000,2,0,3,1,0,'','Today''s fortune is: Good Luck! It''s a good day to go traveling! You might even find your way to the elusive Maho-Maho Kingdom!',0);
INSERT INTO "login_bonus_message_data" VALUES(10,60000,2,0,3,1,0,'','Today''s fortune is: Good Luck! Your work projects will go smoothly! From the depths of Gehenna, a tailwind will whisk you along!',0);
INSERT INTO "login_bonus_message_data" VALUES(11,60000,2,0,3,1,0,'','Today''s fortune is: Good Luck! Be on the lookout for opportunities! A spoonful of pudding might just bring you spiritual happiness!',0);
INSERT INTO "login_bonus_message_data" VALUES(12,60000,2,0,3,2,0,'','Today''s fortune is: Good Luck! Your luck seems to be on the rise! With all the spirits'' protection, you have nothing to fear. ♪',0);
INSERT INTO "login_bonus_message_data" VALUES(13,60000,2,0,4,1,0,'','Today''s fortune is: Fair Luck! Good things await in the morning! Perhaps a friendly big sister will drop by to wake you up?',0);
INSERT INTO "login_bonus_message_data" VALUES(14,60000,2,0,4,1,0,'','Today''s fortune is: Fair Luck! With patience, good things may come! Your lucky animal is the bear. It''ll have your back like a real family!',0);
INSERT INTO "login_bonus_message_data" VALUES(15,60000,2,0,4,1,0,'','Today''s fortune is: Fair Luck! Some fresh air might do you good! If you visit a farm, you''ll have some unique encounters!',0);
INSERT INTO "login_bonus_message_data" VALUES(16,60000,2,0,4,1,0,'','Today''s fortune is: Fair Luck! Your luck is high, but unpredictable! Let''s hope nobody mistakes you for a suspicious creep...',0);
INSERT INTO "login_bonus_message_data" VALUES(17,60000,2,0,4,2,0,'','Today''s fortune is: Fair Luck! All will be well as long as you relax! Idols are your lucky charm. Their peppy songs will bring you joy!',0);
INSERT INTO "login_bonus_message_data" VALUES(18,60000,3,0,0,0,190804,'Karin','How was your fortune today? Whatever your result, I hope you have a wonderful day in store! And do drop by again tomorrow!',2);
INSERT INTO "login_bonus_message_data" VALUES(19,60000,3,7,0,0,190804,'Karin','Did you enjoy our little New Year''s diversion? On behalf of the Guild Association, I wish you the best of fortunes in the year ahead.',3);
INSERT INTO "login_bonus_message_data" VALUES(20,80001,0,1,0,0,101201,'Hatsune','Wow! It''s already been a year since we first met, huh? Feels like I''ve slept most of it away, though...',1);
INSERT INTO "login_bonus_message_data" VALUES(21,80001,0,1,0,0,101201,'Hatsune','Maybe it''s high time that I start cutting down on sleep. That way I can spend more time with you! ♪',2);
INSERT INTO "login_bonus_message_data" VALUES(22,80001,1,1,0,0,103801,'Shiori','A whole year has passed since we met... Time certainly does fly by.',1);
INSERT INTO "login_bonus_message_data" VALUES(23,80001,1,1,0,0,103801,'Shiori','I hope we can spend the next year together, too...',2);
INSERT INTO "login_bonus_message_data" VALUES(24,80001,0,2,0,0,103601,'Kyoka','It''s been a whole year already since we first met each other...',1);
INSERT INTO "login_bonus_message_data" VALUES(25,80001,0,2,0,0,103601,'Kyoka','You seem more reliable now than you did back then. ...So, how about me? Do you think I''ve grown?',2);
INSERT INTO "login_bonus_message_data" VALUES(26,80001,1,2,0,0,102001,'Mimi','Wow, it''s been a whole year since we made friends!',1);
INSERT INTO "login_bonus_message_data" VALUES(27,80001,1,2,0,0,102001,'Mimi','I had so much fun all the times we played together! You''ll keep playing with me, won''t you, mister?',2);
INSERT INTO "login_bonus_message_data" VALUES(28,80001,2,2,0,0,100401,'Misogi','You''ve been falling into my traps for a whole year, huh?',1);
INSERT INTO "login_bonus_message_data" VALUES(29,80001,2,2,0,0,100401,'Misogi','We''ve got a good thing going, so it''d be a shame to stop now!',2);
INSERT INTO "login_bonus_message_data" VALUES(30,80001,0,3,0,0,101001,'Maho','Hard to believe it''s been a whole year since our dramatic meeting, ain''t it?',1);
INSERT INTO "login_bonus_message_data" VALUES(31,80001,0,3,0,0,101001,'Maho','Poor li''l me''s gonna wither up in no time at this rate. Heehee. Just messin'' with ya.',2);
INSERT INTO "login_bonus_message_data" VALUES(32,80001,1,3,0,0,104401,'Illya','So, a year has gone by since our first encounter. I hope your loyalty will not waver in the years to come.',1);
INSERT INTO "login_bonus_message_data" VALUES(33,80001,1,3,0,0,104401,'Illya','Of course, I would not be averse to rewarding you for your service every once in a while! ♪',2);
INSERT INTO "login_bonus_message_data" VALUES(34,80001,2,3,0,0,101701,'Kaori','We''ve been great friends for a pretty long time now! But our adventures together are still just getting started!',1);
INSERT INTO "login_bonus_message_data" VALUES(35,80001,2,3,0,0,101701,'Kaori','You''ll stick with me for a while yet, right? I''m counting on you!',2);
INSERT INTO "login_bonus_message_data" VALUES(36,80001,0,4,0,0,102801,'Saren','A whole year already, huh? Time sure flies.',1);
INSERT INTO "login_bonus_message_data" VALUES(37,80001,0,4,0,0,102801,'Saren','But you know what? It''s all because said time''s been so much fun! So here''s to even more years together!',2);
INSERT INTO "login_bonus_message_data" VALUES(38,80001,1,4,0,0,102501,'Suzume','I''ve done nothing but cause trouble for you over the past year. I''m so sorry...',1);
INSERT INTO "login_bonus_message_data" VALUES(39,80001,1,4,0,0,102501,'Suzume','I want to work hard and make up up for it all, though. So it''d be nice if you stayed nice and close to watch over me. ♪',2);
INSERT INTO "login_bonus_message_data" VALUES(40,80001,0,5,0,0,104601,'Tamaki','Looking back, we sure spent a bunch of good times together, huh?',1);
INSERT INTO "login_bonus_message_data" VALUES(41,80001,0,5,0,0,104601,'Tamaki','The more memories we share, the nyicer it''ll be to look back on them someday and purr!',2);
INSERT INTO "login_bonus_message_data" VALUES(42,80001,1,5,0,0,104801,'Mifuyu','I can''t believe it''s been a year since I took you under my wing. But I still have so much more',1);
INSERT INTO "login_bonus_message_data" VALUES(43,80001,1,5,0,0,104801,'Mifuyu','that I want to teach you! I won''t hold anything back, so try to keep up, all right?',2);
INSERT INTO "login_bonus_message_data" VALUES(44,80001,0,6,0,0,103201,'Akino','A whole year has passed since we first encountered one another...',1);
INSERT INTO "login_bonus_message_data" VALUES(45,80001,0,6,0,0,103201,'Akino','Whoever said that times flies truly hit the nail on the head. Memories this fond simply cannot be bought.',2);
INSERT INTO "login_bonus_message_data" VALUES(46,80001,1,6,0,0,103401,'Yukari','I can''t thank you enough for sticking by me through this whole year in spite of everything.',1);
INSERT INTO "login_bonus_message_data" VALUES(47,80001,1,6,0,0,103401,'Yukari','I might not be at my best all of the time, but I''d be really happy if you were to stay by my side from here on out, too.',2);
INSERT INTO "login_bonus_message_data" VALUES(48,80001,0,7,0,0,107101,'Christina','A year since we first met, eh? Back then, I never dreamed you would become my betrothed.',1);
INSERT INTO "login_bonus_message_data" VALUES(49,80001,0,7,0,0,107101,'Christina','At any rate, I hope you''ll continue to keep me entertained! ☆',2);
INSERT INTO "login_bonus_message_data" VALUES(50,80001,1,7,0,0,104701,'Jun','This year went by so quickly. I feel as though my face has grown less stern since we met... Would you agree?',1);
INSERT INTO "login_bonus_message_data" VALUES(51,80001,1,7,0,0,104701,'Jun','It''s hard to say when I keep it hidden? I suppose you''re right.',2);
INSERT INTO "login_bonus_message_data" VALUES(52,80001,0,8,0,0,103701,'Tomo','It''s been a year already, huh? Feels like I spent the whole time teasing you. It was fun, though! ♪',1);
INSERT INTO "login_bonus_message_data" VALUES(53,80001,0,8,0,0,103701,'Tomo','So let''s keep it up, shall we?',2);
INSERT INTO "login_bonus_message_data" VALUES(54,80001,1,8,0,0,100501,'Matsuri','Wow, a whole year since we met. It kinda feels shorter somehow.',1);
INSERT INTO "login_bonus_message_data" VALUES(55,80001,1,8,0,0,100501,'Matsuri','Maybe that''s ''cause we had so much fun, the days just flew by. I hope you''ll keep on helping me fight evil!',2);
INSERT INTO "login_bonus_message_data" VALUES(56,80001,0,9,0,0,100701,'Miyako','One year passed since we met! Miyako still didn''t pass on,',1);
INSERT INTO "login_bonus_message_data" VALUES(57,80001,0,9,0,0,100701,'Miyako','or come back to life either, but we had lots of fun! As long as Miyako has you and pudding, everything''s good!',2);
INSERT INTO "login_bonus_message_data" VALUES(58,80001,1,9,0,0,103101,'Shinobu','A year has gone by since we met. But according to this reading I just performed,',1);
INSERT INTO "login_bonus_message_data" VALUES(59,80001,1,9,0,0,103101,'Shinobu','it seems we will be together next year as well, and the year after. Haha... I look forward to it.',2);
INSERT INTO "login_bonus_message_data" VALUES(60,80001,0,10,0,0,100901,'Anna','Twelve cycles have passed since your awakening as Sigurd of the Fulgor... Doubtless there will be no end to the battles we face,',1);
INSERT INTO "login_bonus_message_data" VALUES(61,80001,0,10,0,0,100901,'Anna','but as long as you are by my side... I am ready to face even the bonds of matrimony!',2);
INSERT INTO "login_bonus_message_data" VALUES(62,80001,1,10,0,0,101301,'Nanaka','Whew, a whole year since we met! Doesn''t time fly?!',1);
INSERT INTO "login_bonus_message_data" VALUES(63,80001,1,10,0,0,101301,'Nanaka','There''s no end to a perfect duo like ours, though! I''m counting on you, partner!',2);
INSERT INTO "login_bonus_message_data" VALUES(64,80001,0,11,0,0,105101,'Mitsuki','This year went by in the blink of an eye. There are still so many things I need to learn about you...',1);
INSERT INTO "login_bonus_message_data" VALUES(65,80001,0,11,0,0,105101,'Mitsuki','I hope you''ll let me investigate to my heart''s content.',2);
INSERT INTO "login_bonus_message_data" VALUES(66,80001,1,11,0,0,105601,'Ruka','Kind of crazy that it''s already been a year since we met, huh?',1);
INSERT INTO "login_bonus_message_data" VALUES(67,80001,1,11,0,0,105601,'Ruka','Even crazier is that you''ve ended up helping me just as much as I''ve helped you. Sounds like a good relationship to me!',2);
INSERT INTO "login_bonus_message_data" VALUES(68,80001,2,11,0,0,102701,'Eriko','How strange to think it has been a year since we met, my love...',1);
INSERT INTO "login_bonus_message_data" VALUES(69,80001,2,11,0,0,102701,'Eriko','When I''m with you, time moves so fast it loses all meaning. I should research some methods to stop it in its tracks...',2);
INSERT INTO "login_bonus_message_data" VALUES(70,80001,0,12,0,0,102301,'Ayane','I can''t believe it''s already been a whole year. Do I seem like more of an adult than when we first met?',1);
INSERT INTO "login_bonus_message_data" VALUES(71,80001,0,12,0,0,102301,'Ayane','Oh. Same question goes for Pukichi, too.',2);
INSERT INTO "login_bonus_message_data" VALUES(72,80001,1,12,0,0,104201,'Chika','A year truly flies by, doesn''t it? This may sound a bit selfish of me,',1);
INSERT INTO "login_bonus_message_data" VALUES(73,80001,1,12,0,0,104201,'Chika','but it would mean the world to me if you were to stay by my side and watch over me. Ideally forever...',2);
INSERT INTO "login_bonus_message_data" VALUES(74,80001,2,12,0,0,102101,'Kurumi','A whole year''s passed since we first met, but I''m still as useless as ever...',1);
INSERT INTO "login_bonus_message_data" VALUES(75,80001,2,12,0,0,102101,'Kurumi','W-will you still stick by me? I''d really love it if you did...',2);
INSERT INTO "login_bonus_message_data" VALUES(76,80001,0,13,0,0,104901,'Shizuru','It''s the anniversary of our reunion, and I made treats to celebrate! A big cake, some sushi,',1);
INSERT INTO "login_bonus_message_data" VALUES(77,80001,0,13,0,0,104901,'Shizuru','hamburg steaks, curry, stew... And the not-so-secret ingredient in them all is your big sister''s love!',2);
INSERT INTO "login_bonus_message_data" VALUES(78,80001,1,13,0,0,101101,'Rino','Wow, a whole year since we found each other again. After all those days without you,',1);
INSERT INTO "login_bonus_message_data" VALUES(79,80001,1,13,0,0,101101,'Rino','this year felt like something out of a dream! You won''t leave me behind again, right, Big Bro? ♪',2);
INSERT INTO "login_bonus_message_data" VALUES(80,80001,0,14,0,0,100201,'Yui','A whole lot''s happened since we first met, hasn''t it? Plenty of it exciting, plenty of it, uh, nerve-wracking...',1);
INSERT INTO "login_bonus_message_data" VALUES(81,80001,0,14,0,0,100201,'Yui','It''d be really nice if we could... If we could share even more memories together…!',2);
INSERT INTO "login_bonus_message_data" VALUES(82,80001,1,14,0,0,100101,'Hiyori','Hold up, hold up. It''s only been a year since we met?!',1);
INSERT INTO "login_bonus_message_data" VALUES(83,80001,1,14,0,0,100101,'Hiyori','Genuinely feels like we''ve been together forever at this point. Either way. Here''s to another great year!',2);
INSERT INTO "login_bonus_message_data" VALUES(84,80001,2,14,0,0,100301,'Rei','The two of us have come quite a long way since last year, haven''t we?',1);
INSERT INTO "login_bonus_message_data" VALUES(85,80001,2,14,0,0,100301,'Rei','I''m sure we''ll continue to grow as well, so I look forward to the day that I can truly rely on you.',2);
INSERT INTO "login_bonus_message_data" VALUES(86,80001,0,15,0,0,105801,'Pecorine','Thanks for not forgetting about me, even after a whole year!',1);
INSERT INTO "login_bonus_message_data" VALUES(87,80001,0,15,0,0,105801,'Pecorine','I''m sure I''ll be able to say the same next year, and every year after that as well!',2);
INSERT INTO "login_bonus_message_data" VALUES(88,80001,1,15,0,0,105901,'Kokkoro','I am honored to have served you for an entire year, my lord. If I may have one wish,',1);
INSERT INTO "login_bonus_message_data" VALUES(89,80001,1,15,0,0,105901,'Kokkoro','it would be to stay by your side for many years to come. I hope to remain your guide for as long as I am able.',2);
INSERT INTO "login_bonus_message_data" VALUES(90,80001,2,15,0,0,106001,'Karyl','Never thought I''d be stuck with you for a whole year. But hey. It''s been pretty fun.',1);
INSERT INTO "login_bonus_message_data" VALUES(91,80001,2,15,0,0,106001,'Karyl','I''ll stick around for a while longer, so I hope you''re grateful!',2);
