CREATE TABLE 'nyx_drama_data' ('drama_id' INTEGER NOT NULL, 'story_phase' INTEGER NOT NULL, 'title' TEXT NOT NULL, 'sub_title' TEXT NOT NULL, 'condition_unlocked_story_id' INTEGER NOT NULL, 'condition_locked_story_id' INTEGER NOT NULL, PRIMARY KEY('drama_id'));
INSERT INTO "nyx_drama_data" VALUES(101,1,'Special Lesson Report','Cherurun Impact',12,13);
INSERT INTO "nyx_drama_data" VALUES(102,1,'Special Lesson Report','Chloe''s Intuition',13,14);
INSERT INTO "nyx_drama_data" VALUES(103,1,'Special Lesson Report','An Elder''s Pride',14,22);
INSERT INTO "nyx_drama_data" VALUES(201,2,'Mercurius Foundation Journal','Akino Takes Charge',22,23);
INSERT INTO "nyx_drama_data" VALUES(202,2,'Mercurius Foundation Journal','Burning Taiyaki Soul',23,24);
INSERT INTO "nyx_drama_data" VALUES(203,2,'Mercurius Foundation Journal','Barley Broth Power',24,25);
INSERT INTO "nyx_drama_data" VALUES(204,2,'Mercurius Foundation Journal','The Fury of Mifuyu',25,32);
INSERT INTO "nyx_drama_data" VALUES(301,3,'Yuni''s Notes','The Beverage-Snack Conundrum',32,33);
INSERT INTO "nyx_drama_data" VALUES(302,3,'Yuni''s Notes','Nothing Ventured, Nothing Gained',33,34);
INSERT INTO "nyx_drama_data" VALUES(303,3,'Yuni''s Notes','Hazardous Procedures',34,0);
