CREATE TABLE 'srt_action' ('action_name' TEXT NOT NULL, 'inori_action' TEXT NOT NULL, 'dragon_action' TEXT NOT NULL, 'kaya_action' TEXT NOT NULL, 'homare_action' TEXT NOT NULL, 'talk_text_type' INTEGER NOT NULL, 'talk_text' TEXT NOT NULL, 'voice_list' TEXT NOT NULL, PRIMARY KEY('action_name'));
INSERT INTO "srt_action" VALUES('GAME_START','srt_inori_idle','srt_dragon_in,srt_dragon_idle','srt_kaya_idle','',0,'','start_000-start_001,start_002/start_003-boss_emote_064-start_004');
INSERT INTO "srt_action" VALUES('ENEMY_FIRST','srt_inori_idle','srt_dragon_idle','srt_kaya_idle','',2,'Guess I''m up first!','');
INSERT INTO "srt_action" VALUES('ENEMY_TURN1','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'Huh, "{0}"...\nWhat starts with "{1}"...?','');
INSERT INTO "srt_action" VALUES('ENEMY_TURN2','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'Oh, "{0}"?\nHmm, a word that starts with "{1}"...','');
INSERT INTO "srt_action" VALUES('ENEMY_TURN3','srt_inori_idle','srt_dragon_idle','srt_kaya_waiting','',2,'We''re on "{0}"...\nOK, so it''s "{1}" next.','');
INSERT INTO "srt_action" VALUES('ENEMY_HELP','','','srt_kaya_help','srt_homare_help',0,'','sugoyomi_damage_059,sugoyomi_damage_060,sugoyomi_damage_061,sugoyomi_damage_062,sugoyomi_damage_063');
INSERT INTO "srt_action" VALUES('ENEMY_FLASH','','','srt_kaya_flash','',0,'','');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT1','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'I say... "{0}"!','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT2','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'Let''s go with "{0}"!','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT3','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'How about "{0}"?!','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT_GREAT1','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'I like the sound of "{0}"!','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT_GREAT2','srt_inori_react_1,srt_inori_idle','srt_dragon_react_1,srt_dragon_idle','srt_kaya_select_1,srt_kaya_waiting','',2,'Hahah! How about "{0}"?!','sugoyomi_damage_055,sugoyomi_damage_056,sugoyomi_damage_057,sugoyomi_damage_058');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT_WAIT','','','','',-1,'','');
INSERT INTO "srt_action" VALUES('ENEMY_SELECT_N','','','srt_kaya_shock','',1,'Kaya-P, ending with "X" is against the rules...','out_071');
INSERT INTO "srt_action" VALUES('PLAYER_TURN1','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'Oh, "{0}"?\nI need something starting with "{1}," then...','');
INSERT INTO "srt_action" VALUES('PLAYER_TURN2','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'Did you say "{0}"?\nHmm, what starts with "{1}"?','');
INSERT INTO "srt_action" VALUES('PLAYER_TURN3','srt_inori_thinking','srt_dragon_thinking','srt_kaya_waiting','',1,'I see... "{0}."\nNow, what begins with "{1}"...','');
INSERT INTO "srt_action" VALUES('PLAYER_CUTIN_GREAT','','','','',1,'','sugoyomi_cutin_049,sugoyomi_cutin_051,sugoyomi_cutin_053');
INSERT INTO "srt_action" VALUES('PLAYER_CUTIN_PRICONNE','','','','',1,'','sugoyomi_cutin_050,sugoyomi_cutin_052');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'I choose "{0}"!','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'Yes, "{0}" should work!','correct_030-correct_031,correct_035-correct_036');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_GREAT1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'How about "{0}"?!','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_GREAT2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'Heheh! ♪ How about "{0}"?!','correct_030-correct_031,correct_035-correct_036');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_PRECONNE1','srt_inori_select_1,srt_inori_idle','srt_dragon_select_1,srt_dragon_idle','srt_kaya_react_1,srt_kaya_waiting','',1,'Heh heh heh...\nHow does "{0}" sound?!','correct_028-correct_029,correct_032/correct_033-boss_emote_067-correct_034,correct_037-correct_038');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_PRECONNE2','srt_inori_select_2,srt_inori_idle','srt_dragon_select_2,srt_dragon_idle','srt_kaya_react_2,srt_kaya_waiting','',1,'Wait, I''ve got it!\nTake this: "{0}"!','correct_030-correct_031,correct_035-correct_036');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_WAIT','','','','',-1,'','');
INSERT INTO "srt_action" VALUES('PLAYER_MISS','srt_inori_miss,srt_inori_thinking','srt_dragon_miss,srt_dragon_thinking','srt_kaya_react_3,srt_kaya_waiting','',1,'Uerghh! I... I messed up...','mistake_039-mistake_040,mistake_041-mistake_042,mistake_043-mistake_044,mistake_045-mistake_046');
INSERT INTO "srt_action" VALUES('PLAYER_SELECT_N','srt_inori_shock','','srt_kaya_react_4','',2,'C''mon, girl. You know you can''t end in "X."','out_070');
INSERT INTO "srt_action" VALUES('INFEVER','srt_inori_thinking','srt_dragon_thinking','srt_kaya_infever','',1,'This ride isn''t stopping!','rush');
INSERT INTO "srt_action" VALUES('FEVER_SELECT1','srt_inori_select_1','srt_dragon_select_1','','',1,'There''s "{0}"!','correct_028-correct_029,correct_037-correct_038');
INSERT INTO "srt_action" VALUES('FEVER_SELECT2','srt_inori_select_2','srt_dragon_select_2','','',1,'And "{0}"!','correct_030-correct_031,correct_035-correct_036');
INSERT INTO "srt_action" VALUES('FEVER_MISS','srt_inori_miss','srt_dragon_miss','','',1,'Uerghh! I... I messed up...','mistake_039-mistake_040,mistake_041-mistake_042,mistake_043-mistake_044,mistake_045-mistake_046,mistake_047-mistake_048');
INSERT INTO "srt_action" VALUES('FEVER_DAMAGE','srt_inori_fever_attack','srt_dragon_fever_attack','srt_kaya_fever_damage','',1,'Hope you''re ready for this!','rush_attack');
INSERT INTO "srt_action" VALUES('WIN_HP','srt_inori_win_1','srt_dragon_win','srt_kaya_lose','',1,'We''re the winners!','win_005-win_006,win_012-win_013');
INSERT INTO "srt_action" VALUES('WIN_N','srt_inori_win_1','srt_dragon_win','','',1,'We''re the winners!','win_005-win_006,win_012-win_013');
INSERT INTO "srt_action" VALUES('LOSE_MISS','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'Oh nooo... I guess I lose...','lose_017,lose_019,lose_023');
INSERT INTO "srt_action" VALUES('LOSE_N','','srt_dragon_miss','','',1,'Oh nooo... I guess I lose...','lose_017,lose_019,lose_023');
INSERT INTO "srt_action" VALUES('TIMEUP','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'W-we''re out of time?! No way...','lose_025/lose_026-boss_emote_068,lose_021');
INSERT INTO "srt_action" VALUES('LOSE_MISS2','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'Oh nooo... I guess I lose...\nAnd "{0}" was right there, too...','lose_017,lose_019,lose_023');
INSERT INTO "srt_action" VALUES('LOSE_N2','','srt_dragon_miss','','',1,'Oh nooo... I guess I lose...\nAnd "{0}" was right there, too...','lose_017,lose_019,lose_023');
INSERT INTO "srt_action" VALUES('TIMEUP2','srt_inori_lose','srt_dragon_lose','srt_kaya_win','',1,'W-we''re out of time?! No way...\nAnd "{0}" was right there, too...','lose_025/lose_026-boss_emote_068,lose_021');
